name: Build NX Locale Switcher

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  nx-locale-switcher:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Building nx-locale-switcher
      run: |
        make -j$(nproc)

    - uses: actions/upload-artifact@master
      with:
        name: nx-locale-switcher
        path: nx-locale-switcher.nro
